
// Worker status
export const TRIGGER_RUN_HISTORY_WORKER_STATUS_UNPROCESSED = 0;
export const TRIGGER_RUN_HISTORY_WORKER_STATUS_UNDER_PROCESSING = 1;
export const TRIGGER_RUN_HISTORY_WORKER_STATUS_SUCCESS = 2;
export const TRIGGER_RUN_HISTORY_WORKER_STATUS_FAILURE = 3;

export const IFTTT_ACTION_RUN_HISTORY_WORKER_STATUS_UNPROCESSED = 0;
export const IFTTT_ACTION_RUN_HISTORY_WORKER_STATUS_UNDER_PROCESSING = 1;
export const IFTTT_ACTION_RUN_HISTORY_WORKER_STATUS_SUCCESS = 2;
export const IFTTT_ACTION_RUN_HISTORY_WORKER_STATUS_FAILURE = 3;

